/* Name:Matthew Marks   
Date:4/1/2023
Description: Write a program that plays a fun game with the user. 
Grade: C
*/

/* IMPLEMENT THE MEHODS IN THE GIVEN ORDER*/
import java.util.*;
public class GameMarks
{ 
  //No code here
}
class Game {    
   public static void main(String[] args) {
      Scanner kb = new Scanner(System.in);
      interact(kb);
      action(kb);
   }
   
   
     /* 
     The purpose for this method is to ask the user to enter a positive integer value
     This method gets two paramters Scanner and a string. The string s holds the message being displayed for the user
      This method asks the user to enter a positive number. 
      As long as the entered value is not positive, the method will keep asking the user
      
      */  
  public static int prompt(Scanner kb, String s) 
{
    int input = 0;
    while (true) 
    {
        System.out.print(s);
        input = kb.nextInt();
        if (input > 0) 
        {
            break;
        }
        System.out.println("Invalid input! Please enter a positive number.");
    }
    return input;
}
 /* This method displays the intro given in the sample output. It must match excatly with the sample output. Refer to the provided
   output
   */
public static void interact(Scanner kb) 
{
    System.out.println("Welcome to the Fun Game!");
    System.out.println("=========================");
    System.out.println("I'm thinking of a number between two values that you will enter.");
    System.out.println("You need to guess what that number is in as few attempts as possible.");
    System.out.println("If you guess correctly, you win!");
    System.out.println("Are you ready to start? Let's go!");
    System.out.println();
    System.out.println();
}
/* this method gets two numbers called guess and randNum
    if guess is greater than randNum then return "Lower"
    else if guess is less than randNum return "Higher"
    else return match*/
public static String match(int guess, int randNum) 
{
    if (guess > randNum) 
    {
        return "Lower";
    } 
    else if (guess < randNum) 
    {
        return "Higher";
    } 
    else 
    {
        return "Match";
    }
}
/*
  this method displays the result on the screen. 
  This method gets two parameters representing the number of the games the person played and the total guesses 
  made for all the games played
*/
public static void report(int numGames, int totGuesses) 
{
    System.out.println("You played " + numGames + " games and made " + totGuesses + " guesses in total.");
    System.out.println("Your average number of guesses per game is " + (double)totGuesses/numGames + ".");
    System.out.println("Thanks for playing! Goodbye!");
}
/*This method plays the game. it will generate a random number between min and max.
     asks the user to guess the number generated by the computer. As long as the user is not making the correct guess
     will keep propmting the user. Once the user makes a correct guess, it will end the game
     Also it keeps track of the number of the guesses that the user has made. 
     Return: This method returns the number of the guesses the person made 
     Refer to the sample output          
    */ 
public static int funGame(Scanner console, int min, int max) 
{
    Random r = new Random();
    int randNum = r.nextInt(max - min + 1) + min;
    int guess = 0;
    int numGuesses = 0;
    console.nextLine();
    System.out.println("I'm thinking of a number between " + min + " and " + max + ".");
    System.out.println("Give me a few seconds to think...");
    console.nextLine();
    System.out.println("OK! I'm ready! What's your guess?");
    while (true) 
    {
        guess = console.nextInt();
        numGuesses++;
        String result = match(guess, randNum);
        if (result.equals("Match")) 
        {
            System.out.println("Congratulations! You guessed my number in " + numGuesses + " guesses!");
            break;
        } 
        else 
        {
            System.out.println("Sorry, your guess is " + result + ". Try again.");
        }
    }
    System.out.println();
    return numGuesses;
}
/* This method calls the other methods to get the game started.*/
public static void action(Scanner console)  
{      
    int numGames = 0;
    int totGuesses = 0;
    String repeat = "yes";           
    while (repeat.equalsIgnoreCase("yes")) 
    {
        int min = prompt(console, "Enter a low value: ");
        int max = prompt(console, "Enter a high value: ");
        while (max < min) 
        {
            System.out.println("Invalid input! The high value must be greater than or equal to the low value. Start over");
            max = prompt(console, "Enter a high value: ");
        }
        int numGuesses = funGame(console, min, max);
        totGuesses += numGuesses;
    }
   }     
}